### ISSUE TITLE
Router loses parts of lare request bodies.

### ISSUE THREAD

**Issue by logi** [networknt/light-router#22]
I have a service which accepts POSTed JSON payloads which are parsed by `BodyHandler`. It has been stress tested with multiple concurrent processes which repeatedly upload the same payloads ranging in in size from 2.8K to 109K of test data and it is reliable after tens of thousands of iterations.

Adding a light-router (port 8080) in front of this, even with only a single instance of the service (port 2400) again works reliably for the smaller payloads of 2.8K. Slowly increasing the payload size and running the tight upload loop, we start getting 503 responses when we cross the 32K boundary.

Running the service in the IDEA debugger with a router in front of it we see that the BodyHandler fails to parse the payload and copying the string to a file and comparing with the original payload, we see that there is a chunk of just over 16K missing from the string being parsed compared to the payload that was sent.

Looking at the router code my initial suspicion is that the connection caching in `RouterProxyClient` is not thread safe and bad things start happening when the payload size exceeds the size of a buffer somewhere.

Some observations:
- The limits are a tad over 32K and the missing data is just over 16K in utf-8 encoded files with some amount of non-ascii text, so these problems might be happening on some text-buffer level rather than a byte-buffer level to get nice round powers of 2.
- The larger the payloads are, then more likely they are to fail.
- Adding a 1 second sleep between calls does not make the problem go away.

Making a stand-alone test case for this will be a bit tricky so I'm opening the issue without one before the week-end while it's fresh in my mind.

**Comment by NicholasAzar** [comment]
@logi this is really important to get fixed. Thanks for bringing it up

**Comment by logi** [comment]
I should add that this was all on 1.5.18 as I've had some config problems on 1.5.19

**Comment by stevehu** [comment]
I have successfully reproduced the issue in the development branch. Debugging...

**Comment by stevehu** [comment]
This is fixed in the light-4j client module by making the bufferSize configurable for the default buffer pool. More info can be found at https://github.com/networknt/light-example-4j/tree/develop/router

**Comment by logi** [comment]
Yeah, that will do as a work-around, but the bug still remains.

**Comment by stevehu** [comment]
@logi to archive high performance with less memory assumption, we are using direct buffer with zero copy. During the client initialization, a pool of direct buffers are allocated and the pool is shared by all threads. As we donot know how big the application request, we can only set a default which covers majority of applications. For applications with bigger requests, you just need to change the configuration to allocate bigger buffers. It is just like the default JVM settings are suitable for most applications but might run out of memory if you have a big app. 

I am open for all options but I don't see we can go back to jvm buffers. What we can do is to make the error message more clear and point to the config property. Also make the document more clear so developers are aware of this config. What do you think?

**Comment by stevehu** [comment]
Yes. It is passthrough on the router as we are using os direct buffer to the socket. But in Java, you have to create the buffer before hand.

**Comment by logi** [comment]
I guess I should read up on this, but are the direct buffers consuming memory or just address space?

**Comment by stevehu** [comment]
It consumes memory in the operating system space not in the user space.

**Comment by stevehu** [comment]
This issue has been removed by add bufferSize in client.yml for certain use cases and add encode-decode for the request's body encoded with gzip.
